### ISSUE TITLE
Add MinerMore Pool for Raven Coin - (A Message from an advanced miner that loves this platform)

### ISSUE THREAD

**Issue by stabbed** [SaladTechnologies/salad-applications#485]
this may not be an actual issue but it's a very much needed request that have been requested multiple times by me and a friend on discord that started mining Raven Coin outside of salad (only because of this mainly) and he got paid up to 5 RVN's in a single hour because the MinerMore pool is not as complicated as the NiceHash's one in the process of paying you crypto for what you mined there it's more like renting your hashing power but on MinerMore it's very different and thus why double the earnings there with a 1060 6GB it could be up to $1.6 a day he's got proof and i have proved it myself to seniorquico which is apparently one of your developers in discord that he's actually steadily earning that much which is very high and very fast at submitting shares specially for that gpu that isn't as good in compute as some AMD cards or say the new "Turing" architecture so it's the best pool for Raven Coin despite that mining the coin itself is still possible through salad and it pays 20% more than ethereum but it's still on NiceHash's stratum which is the whole point of this request
sadly that money cannot be transferred into salad balance cause of the current pools you have supported
and whenever i bring this up with any staff or developer their excuse is "We're working on other stuff" well work on this as well god damn it
i'm a valuable customer and iv'e made a load of money in my salad account thus i'm making you money along the process so i don't think you would want to lose me and make yourself look bad in front of your community ^^

**Comment by javaxxxxx** [comment]
I actually agree

there's no point of only having NiceHash :)
