### ISSUE TITLE
Offerwalls tab, incorrect info

### ISSUE THREAD

**Issue by Walker21390** [SaladTechnologies/salad-applications#522]
In the offerwalls tab, it says: "BlueStacks or other device emulators may not be supported by offerwall providers"
I tried all offerwalls with BlueStacks and they all work fine : )
![image](https://user-images.githubusercontent.com/71191962/93007829-b8ddb780-f56d-11ea-92db-6f3c2e3e440f.png)

**Comment by Vukky123** [comment]
Not a Salad developer, but it says **may**
It never said **will** 👀

**Comment by Walker21390** [comment]
**_Shut_**

Ok ill close
